# Import dependencies

In [247]:
import os 
import csv
import pandas as pd
import requests
import datetime as dt

# Data Files

In [248]:
vancouver_01_path = os.path.join("Resources","Mobi_System_Data_2019-01.csv")
vancouver_02_path = os.path.join("Resources","Mobi_System_Data_2019-02.csv")
vancouver_03_path = os.path.join("Resources","Mobi_System_Data_2019-03.csv")
vancouver_04_path = os.path.join("Resources","Mobi_System_Data_2019-04.csv")
vancouver_05_path = os.path.join("Resources","Mobi_System_Data_2019-05.csv")
vancouver_06_path = os.path.join("Resources","Mobi_System_Data_2019-06.csv")
vancouver_07_path = os.path.join("Resources","Mobi_System_Data_2019-07.csv")
vancouver_08_path = os.path.join("Resources","Mobi_System_Data_2019-08.csv")
vancouver_09_path = os.path.join("Resources","Mobi_System_Data_2019-09.csv")
vancouver_10_path = os.path.join("Resources","Mobi_System_Data_2019-10.csv")
vancouver_11_path = os.path.join("Resources","Mobi_System_Data_2019-11.csv")
vancouver_12_path = os.path.join("Resources","Mobi_System_Data_2019-12.csv")

# Read Data Files

In [249]:
vancouver_01 = pd.read_csv(vancouver_01_path, encoding="utf=8")
vancouver_02 = pd.read_csv(vancouver_02_path, encoding="utf=8")
vancouver_03 = pd.read_csv(vancouver_03_path, encoding="utf=8")
vancouver_04 = pd.read_csv(vancouver_04_path, encoding="utf=8")
vancouver_05 = pd.read_csv(vancouver_05_path, encoding="utf=8")
vancouver_06 = pd.read_csv(vancouver_06_path, encoding="utf=8")
vancouver_07 = pd.read_csv(vancouver_07_path, encoding="utf=8")
vancouver_08 = pd.read_csv(vancouver_08_path, encoding="utf=8")
vancouver_09 = pd.read_csv(vancouver_09_path, encoding="utf=8")
vancouver_10 = pd.read_csv(vancouver_10_path, encoding="utf=8")
vancouver_11 = pd.read_csv(vancouver_11_path, encoding="utf=8")
vancouver_12 = pd.read_csv(vancouver_12_path, encoding="utf=8")

In [250]:
vancouver_01

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (C),Return temperature (C),Stopover duration,Number of stopovers,Manager
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,714.0,177,3826,4000,9,9,0,0,False
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,859.0,221,3705,3850,9,11,0,0,False
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,6691.0,3272,3842,4059,10,11,370,1,False
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,473.0,157,4029,4140,9,10,0,0,False
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,1404.0,516,3990,4100,9,10,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36745,1/1/2019 0:00,1/1/2019 1:00,511.0,0105 Stanley Park - Totem Poles,0084 Sunset Beach West,24 Hour,4569.0,1382,4076,4214,4,6,0,0,False
36746,1/1/2019 0:00,1/1/2019 0:00,723.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Corporate Standard,3689.0,1009,3750,3969,5,7,0,0,False
36747,1/1/2019 0:00,1/1/2019 1:00,938.0,0139 Burrard & 4th,0167 Cordova & Columbia,365 Day Founding Plus,4737.0,1144,3589,3848,5,8,0,0,False
36748,1/1/2019 0:00,1/1/2019 0:00,1450.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Day Founding Plus,3702.0,1105,3568,3876,5,6,0,0,False
36749,1/1/2019 0:00,1/1/2019 1:00,161.0,0098 Carrall & Hastings,0012 Dunsmuir & Richards,24 Hour,1686.0,1300,3823,3964,5,5,0,0,False

In [251]:
# # drop columns
columns=["Departure", "Return", "Bike", "Departure station", "Return station", "Membership type", "Duration (sec.)"]
vancouver_01 = vancouver_01[columns]
vancouver_02= vancouver_02.rename(columns={"Membership Type": "Membership type"})
vancouver_02 = vancouver_02[columns]
vancouver_03 = vancouver_03[columns]
vancouver_04 = vancouver_04[columns]
vancouver_05 = vancouver_05[columns]
vancouver_06 = vancouver_06[columns]
vancouver_07 = vancouver_07[columns]
vancouver_08 = vancouver_08[columns]
vancouver_09 = vancouver_09[columns]
vancouver_10 = vancouver_10[columns]
vancouver_11 = vancouver_11[columns]
vancouver_12= vancouver_12.rename(columns={"Membership Type": "Membership type"})
vancouver_12 = vancouver_12[columns]

In [252]:
vancouver_01

,Departure,Return,Bike,Departure station,Return station,Membership type,Duration (sec.)
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516
...,...,...,...,...,...,...,...
36745,1/1/2019 0:00,1/1/2019 1:00,511.0,0105 Stanley Park - Totem Poles,0084 Sunset Beach West,24 Hour,1382
36746,1/1/2019 0:00,1/1/2019 0:00,723.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Corporate Standard,1009
36747,1/1/2019 0:00,1/1/2019 1:00,938.0,0139 Burrard & 4th,0167 Cordova & Columbia,365 Day Founding Plus,1144
36748,1/1/2019 0:00,1/1/2019 0:00,1450.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Day Founding Plus,1105
36749,1/1/2019 0:00,1/1/2019 1:00,161.0,0098 Carrall & Hastings,0012 Dunsmuir & Richards,24 Hour,1300

In [253]:
#Add new column:location_id
vancouver_01["location_id"]=2
vancouver_02["location_id"]=2
vancouver_03["location_id"]=2
vancouver_04["location_id"]=2
vancouver_05["location_id"]=2
vancouver_06["location_id"]=2
vancouver_07["location_id"]=2
vancouver_08["location_id"]=2
vancouver_09["location_id"]=2
vancouver_10["location_id"]=2
vancouver_11["location_id"]=2
vancouver_12["location_id"]=2

<ipython-input-253-4ba426c46331>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vancouver_01["location_id"]=2

In [254]:
vancouver_01

,Departure,Return,Bike,Departure station,Return station,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
36745,1/1/2019 0:00,1/1/2019 1:00,511.0,0105 Stanley Park - Totem Poles,0084 Sunset Beach West,24 Hour,1382,2
36746,1/1/2019 0:00,1/1/2019 0:00,723.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Corporate Standard,1009,2
36747,1/1/2019 0:00,1/1/2019 1:00,938.0,0139 Burrard & 4th,0167 Cordova & Columbia,365 Day Founding Plus,1144,2
36748,1/1/2019 0:00,1/1/2019 0:00,1450.0,0088 Harwood & Bute,0218 Carrall & Seawall,365 Day Founding Plus,1105,2
36749,1/1/2019 0:00,1/1/2019 1:00,161.0,0098 Carrall & Hastings,0012 Dunsmuir & Richards,24 Hour,1300,2

In [255]:
#performing concatenation
vancouver = [vancouver_01,vancouver_02,vancouver_03,vancouver_04,vancouver_05,vancouver_06,
             vancouver_07,vancouver_08,vancouver_09,vancouver_10,vancouver_11,vancouver_12]
bike_share = pd.concat(vancouver).drop_duplicates().reset_index(drop=True)
bike_share

,Departure,Return,Bike,Departure station,Return station,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,365 Plus,167,2

In [256]:
# remove rows with null values
bike_share = bike_share.dropna()

In [257]:
bike_share

,Departure,Return,Bike,Departure station,Return station,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,365 Plus,167,2

In [258]:
#Renaming columns
bike_share = bike_share.rename(columns={"Bike": "bike_id",
                                        "Departure station":"start station id",
                                        "Return station":"end station id",
                                        "Departure":"starttime",
                                        "Return":"stoptime",
                                        "Duration (sec.)":"tripduration",
                                        "Membership type":"usertype"})

bike_share

,starttime,stoptime,bike_id,start station id,end station id,usertype,tripduration,location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,365 Plus,167,2

In [259]:
#total count of list
bike_share.count()

starttime           891010
stoptime            891010
bike_id             891010
start station id    891010
end station id      891010
usertype            891010
tripduration        891010
location_id         891010
dtype: int64

In [261]:
#Bike ID
bikes = pd.DataFrame(bike_share[["bike_id","location_id"]])
bikes = bikes.drop_duplicates().reset_index(drop=True)

In [262]:
bikes

      bike_id  location_id
0       388.0            2
1      1880.0            2
2       779.0            2
3      2123.0            2
4       444.0            2
...       ...          ...
2006   1805.0            2
2007    638.0            2
2008   1853.0            2
2009   1819.0            2
2010   1750.0            2

[2011 rows x 2 columns]

In [264]:
#drop bad dates
bike_share= bike_share.loc[(bike_share["stoptime"]!= "1900-01-00 0:00")]
bike_share

,starttime,stoptime,bike_id,start station id,end station id,usertype,tripduration,location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,365 Plus,167,2

In [265]:
# Display Data Table for Preview
bike_share["Member Type"]=bike_share["Membership type"]
bike_share

KeyError: 'Membership type'

In [225]:
# drop columns
i =["Member Type"]
bike_share=bike_share.drop(columns=i)

In [226]:
bike_share

,Departure,Return,Bike_id,start station id,end station id,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,365 Plus,167,2

In [227]:
#Membership :User type
usertype = pd.DataFrame(bike_share[["Membership type","location_id"]])
usertype = usertype.drop_duplicates().reset_index(drop=True)
usertype

                   Membership type  location_id
0                     365 Standard            2
1                         365 Plus            2
2           Vancity Community Pass            2
3           365 Day Pass Plus SALE            2
4        365 Day Founding Standard            2
5       365 Day Pass Standard SALE            2
6           365 Corporate Standard            2
7                           90 Day            2
8               365 Corporate Plus            2
9            365 Day Founding Plus            2
10           Archived Monthly Plus            2
11          Archived Monthly Basic            2
12  365 Corporate Standard Renewal            2
13       Archived Monthly Standard            2
14      365 Corporate Plus Renewal            2
15                         24 Hour            2
16                             VIP            2
17                     30 Day Pass            2
18                Single Trip Pass            2
19            Shared Mobility Pass            2
20                 Archived 90 Day            2

In [229]:
#Getting Departure station id
bike_share["start station id"]= bike_share["start station id"].str.split(" ", n = 1, expand = True)

In [230]:
bike_share

,Departure,Return,Bike_id,start station id,end station id,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198,0298 6th & Carolina,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193,0173 1st & Columbia,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063,0143 South False Creek Seawall,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064,0078 Nelson & Mainland,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060,0196 Drake & Hornby,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187,0032 Comox & Denman,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024,0208 Arbutus Greenway & Broadway,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099,0096 Nicola & Robson,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193,0174 1st & Manitoba,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193,0174 1st & Manitoba,365 Plus,167,2

In [231]:
# Getting Return station id
bike_share["end station id"]= bike_share["end station id"].str.split(" ", n = 1, expand = True)

In [232]:
bike_share

,Departure,Return,Bike_id,start station id,end station id,Membership type,Duration (sec.),location_id
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198,0298,365 Standard,177,2
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193,0173,365 Plus,221,2
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063,0143,Vancity Community Pass,3272,2
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064,0078,365 Day Pass Plus SALE,157,2
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060,0196,365 Day Pass Plus SALE,516,2
...,...,...,...,...,...,...,...,...
891714,2019-12-01 0:00,2019-12-01 0:00,631.0,0187,0032,30 Day Pass,327,2
891715,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024,0208,365 Standard,1473,2
891716,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099,0096,365 Day Founding Standard,358,2
891717,2019-12-01 0:00,2019-12-01 0:00,985.0,0193,0174,365 Plus,163,2
891718,2019-12-01 0:00,2019-12-01 0:00,291.0,0193,0174,365 Plus,167,2

In [233]:
# Save Combined DataFrames to CSV
bike_share.to_csv("Vancouver_bikeshare.csv", index=False, header=True)